config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :incomes
  resources :expenses
  resources :accounts
  resources :orders
  post 'cw_pages/thank_you'
  get 'cw_pages/about'
  get 'cw_pages/contact'
  get 'cw_pages/index'
  root 'cw_pages#index'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.includes(:product).all
  end

   def show
     @order = Order.find(params[:id])
   end

   def new
   end

   def create
   end

   def destroy
   end

end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price%>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/index.html.erb
<div class="row">
  <% @orders.each do |order| %>
    <div class="col-sm-2 col-md-4">
      <h1>
        Order # <%= order.id %>:
        <%= image_tag(order.product.image_url, class: "img-responsive") %>
        <%= link_to order.product.name, order %>
      </h1>
      <p><%= order.product.description %></p>
      <strong>$ <%= order.product.price %></strong>
    </div><!-- /col -->
  <% end %>
</div>


<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<div class="container">
  <h2>Order Information</h2>
  <strong>Order ID: </strong><%= @order.id %>
  <%= image_tag(@order.product.image_url, class: "img-responsive") %>
  <strong>Product Name: </strong><%= @order.product.name %>
  <strong>Product Price: </strong><%= number_to_currency(@order.product.price/100.to_f) %>
  <strong>Total Price: </strong><%= number_to_currency(@order.total/100.to_f) %>
</div>


<%= link_to 'Edit', edit_order_path(@product) %> |
<%= link_to 'Back', orders_path %>