config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :incomes
  resources :expenses
  resources :accounts
  resources :orders
  post 'cw_pages/thank_you'
  get 'cw_pages/about'
  get 'cw_pages/contact'
  get 'cw_pages/index'
  root 'cw_pages#index'
  resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_, :name, :start_date, :gross_billing, :service_times, :prime_contact, :contact_ph, :contact_email)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_ %>
    <%= form.text_field :account_ %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :gross_billing %>
    <%= form.text_field :gross_billing %>
  </div>

  <div class="field">
    <%= form.label :service_times %>
    <%= form.text_field :service_times %>
  </div>

  <div class="field">
    <%= form.label :prime_contact %>
    <%= form.text_field :prime_contact %>
  </div>

  <div class="field">
    <%= form.label :contact_ph %>
    <%= form.text_field :contact_ph %>
  </div>

  <div class="field">
    <%= form.label :contact_email %>
    <%= form.text_field :contact_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>
<div class="acct_container table-responsive">
<table>
  <thead>
    <tr>
      <th>Account </th>
      <th>Start date</th>
      <th>Gross billing</th>
      <th>Service times</th>
      <th>Prime contact</th>
      <th>Contact ph</th>
      <th>Contact email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.account_ %></td>
        <td><%= account.start_date %></td>
        <td><%= account.gross_billing %></td>
        <td><%= account.service_times %></td>
        <td><%= account.prime_contact %></td>
        <td><%= account.contact_ph %></td>
        <td><%= account.contact_email %></td>
        <td class="accts_show"><%= link_to 'View', account %></td>
        <td class="accts_show"><%= link_to 'Edit', edit_account_path(account) %></td>
        <td class="accts_show"><%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<div class="accts_show"><%= link_to 'New Account', new_account_path %></div>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account :</strong>
  <%= @account.account_ %>
</p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @account.start_date %>
</p>

<p>
  <strong>Gross billing:</strong>
  <%= @account.gross_billing %>
</p>

<p>
  <strong>Service times:</strong>
  <%= @account.service_times %>
</p>

<p>
  <strong>Prime contact:</strong>
  <%= @account.prime_contact %>
</p>

<p>
  <strong>Contact ph:</strong>
  <%= @account.contact_ph %>
</p>

<p>
  <strong>Contact email:</strong>
  <%= @account.contact_email %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>